name: image_compare
description: Dart package to compare images
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image: ^3.0.2
  path: ^1.7.0
  tuple: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.0

assets:
  - assets/
  - assets/drawings/
  - assets/animals/
  - assets/objects/
  
